
var mesh_instance = null
var collider = null
var pos = Vector2(0,0)

func update_collider():
	clear_collider()
	if collider == null:
		# TODO This "helper" is very confusing.
		# It does stuff behind the scenes I had no idea of,
		# and returns nothing :/
		mesh_instance.create_trimesh_collision()
		collider = _get_collider()

func clear_collider():
	if collider != null:
		collider.queue_free()
		collider = null

# Helper to get the collider generated by the other helper...
func _get_collider():
	var cc = mesh_instance.get_child_count()
	if cc == 0:
		return null
	# Get last node, assuming it's the latest generated collider
	var b = mesh_instance.get_child(cc-1)
	if b extends StaticBody:
		return b
	print("ERROR: terrain.gd: could not retrieve generated trimesh collision")
	return null

